"""
model_loader.py — RescueBOT Automatic Model Loader
Auto-generated by init_project.py. Do not edit manually.
"""
import pathlib
import logging
import yaml
import json

ROOT = pathlib.Path(__file__).parent.parent.parent
log = logging.getLogger(__name__)

_models = {}
_config = None

def get_config():
    global _config
    if _config is None:
        cfg_path = ROOT / "config.yaml"
        with open(cfg_path) as f:
            _config = yaml.safe_load(f)
    return _config

def load_yolo(model_key: str):
    """Load (or return cached) a YOLO model by config key."""
    if model_key in _models:
        return _models[model_key]
    cfg = get_config()
    model_cfg = cfg["models"].get(model_key, {})
    path = ROOT / model_cfg.get("path", "")
    if not path.exists():
        log.warning(f"Model {model_key} not found at {path}. Fallback active.")
        return None
    try:
        from ultralytics import YOLO
        device = cfg["inference"].get("device", "cpu")
        model = YOLO(str(path))
        _models[model_key] = model
        log.info(f"Loaded {model_key} from {path.name}")
        return model
    except Exception as e:
        log.error(f"Failed to load {model_key}: {e}")
        return None

def load_mediapipe_hands():
    """Load MediaPipe Hands solution."""
    if "mp_hands" in _models:
        return _models["mp_hands"]
    try:
        import mediapipe as mp
        hands = mp.solutions.hands.Hands(
            static_image_mode=False,
            max_num_hands=2,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5,
        )
        _models["mp_hands"] = hands
        return hands
    except Exception as e:
        log.error(f"MediaPipe Hands load failed: {e}")
        return None

def load_mediapipe_pose():
    """Load MediaPipe Pose solution."""
    if "mp_pose" in _models:
        return _models["mp_pose"]
    try:
        import mediapipe as mp
        pose = mp.solutions.pose.Pose(
            static_image_mode=False,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5,
        )
        _models["mp_pose"] = pose
        return pose
    except Exception as e:
        log.error(f"MediaPipe Pose load failed: {e}")
        return None

def load_all():
    """Pre-load all models. Call at server startup."""
    log.info("Pre-loading all AI models...")
    load_yolo("person")
    load_yolo("pose")
    load_yolo("fire")
    load_yolo("smoke")
    load_mediapipe_hands()
    load_mediapipe_pose()
    log.info(f"Models loaded: {list(_models.keys())}")
    return _models

def get_registry():
    """Return the model registry from JSON."""
    reg_path = ROOT / "models" / "model_registry.json"
    if reg_path.exists():
        with open(reg_path) as f:
            return json.load(f)
    return {}

def diagnostics():
    """Quick diagnostics: return loaded model states."""
    return {k: type(v).__name__ for k, v in _models.items()}
